---

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/extensions: 0
  import/no-unresolved: 0
  no-param-reassign: 0
  comma-dangle: 0
